configfile: "config/config.yaml"


SAMPLES = config["samples"]

rule all:
        input:
                "results/multiqc/multiqc_report.html"

#FASTP(trimming)
rule fastp:
        input:
                r1 = "data/raw/{sample}_R1.fastq.gz",
                r2 = "data/raw/{sample}_R2.fastq.gz"
        output:
                r1 = "results/trimmed/{sample}_R1.trimmed.fastq.gz",
                r2 = "results/trimmed/{sample}_R2.trimmed.fastq.gz",
                html = "results/trimmed/{sample}_fastp.html",
                json = "results/trimmed/{sample}_fastp.json"
        shell:
                """
                mkdir -p results/trimmed
                fastp -i {input.r1} -I {input.r2} \
                      -o {output.r1} -O {output.r2}\
                      -h {output.html} -j {output.json}
                """
#FASTQ
rule fastqc:
	input:
		r1="results/trimmed/{sample}_R1.trimmed.fastq.gz",
		r2="results/trimmed/{sample}_R2.trimmed.fastq.gz"
	output:
		"results/fastqc/{sample}_R1.trimmed_fastqc.html",
		"results/fastqc/{sample}_R2.trimmed_fastqc.html"
	shell:
		"""
		mkdir -p results/fastqc 
		fastqc {input.r1} {input.r2} -o results/fastqc/
		"""

#multiqc
rule multiqc:
	input:
		expand([
			"results/fastqc/{sample}_R1.trimmed_fastqc.html",
			"results/fastqc/{sample}_R2.trimmed_fastqc.html"],
			sample=SAMPLES)
	output:
		"results/multiqc/multiqc_report.html"
	shell:
		"""
		mkdir -p results/multiqc
		multiqc results/fastqc/ -o results/multiqc/
		"""
